version: "3"

services:

  main:
    build:
      context: "../../"
    image: moleculer-blog
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://mongo/moleculer-blog"

    env_file: env
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ../../db:/data/db