version: "3.0"

services:

  api:
    image: moleculer-blog
    expose:
      - "4000"
    ports:
      - "4000:4000"
    environment:
      MOL_NODE_ID: "node-api"
      MOL_SERVICES: api.service
      MOL_APIGW_PORT: 4000
    env_file: micro.env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  posts:
    image: moleculer-blog
    environment:
      MOL_NODE_ID: "node-posts"
      MOL_SERVICES: posts.service
    env_file: micro.env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  users:
    image: moleculer-blog
    environment:
      MOL_NODE_ID: "node-users"
      MOL_SERVICES: users.service
    env_file: micro.env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    #deploy:
    #  replicas: 2

  comments:
    image: moleculer-blog
    environment:
      MOL_NODE_ID: "node-comments"
      MOL_SERVICES: comments.service
    env_file: micro.env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    # hostname: nats-server

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    # hostname: redis-server