version: "3.0"

services:

  api:
    image: moleculer-blog
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: env
    environment:
      NODEID: "node-api"
      SERVICES: api
      PORT: 3000
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  group1:
    image: moleculer-blog
    env_file: env
    environment:
      NODEID: "node-group1"
      SERVICES: posts,users,comments
    links:
      - nats
      - redis
      - mongo      
    depends_on:
      - nats
      - redis
      - mongo      
    #deploy:
    #  replicas: 2

  nats:
    image: nats

  redis:
    image: redis:alpine

  mongo:
    image: mongo
    volumes:
      - ../../db:/data/db    