version: "3.0"

services:

  api:
    image: moleculer-blog
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      NODEID: "node-api"      
      SERVICES: api.service
      PORT: 5000
    env_file: env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  group1:
    image: moleculer-blog
    environment:
      NODEID: "node-group1"
      SERVICES: "posts.service,users.service,comments.service"
    env_file: env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    #deploy:
    #  replicas: 2

  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    # hostname: nats-server

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    # hostname: redis-server