version: "3.0"

services:

  api:
    image: moleculer-blog
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODEID: "node-api"
      SERVICEDIR: services
      SERVICES: api
      PORT: 3000
    env_file: env
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis

  group1:
    image: moleculer-blog
    environment:
      NODEID: "node-group1"
      SERVICEDIR: services
      SERVICES: posts,users,comments
    env_file: env
    links:
      - nats
      - redis
      - mongo      
    depends_on:
      - nats
      - redis
      - mongo      
    #deploy:
    #  replicas: 2

  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    volumes:
      - ../db:/data/db    